
server:
  port: 9020
  tomcat:
    max-connections: 1
    accept-count: 0
    max-threads: 1

app:
  name: base-web
  error-log:
    collection: error_log
    expireDay: 30

login:
  maxStillState: 3000000 # ms
  maxReuse: 1

web:
  accessInterval: 1000 # ms
  isLoose: true

redis:
  host: localhost
  port: 6379
  password: 123
  database: 3
  max-active: 200
  max-wait: -1
  max-idle: 8
  timeout: 0
  connectionPoolSize: 400

ais.mq:
  host: localhost # connection host
  port: 5672 # 5772 # connection port
  username: guest
  password: guest
  concurrency: 10
  maxConcurrency: 10
  virtualHost: /api-game-2

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: true
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true


datasources:
  statu: 1
  instants:
    instant-1:
      url: jdbc:mysql://localhost:3306/users?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      maxActive: 100
      maxIdle: 10
      minIdle: 5
      type: com.alibaba.druid.pool.DruidDataSource
      isDefault: true

#jap:
#  enable: true


mongo:
  host: 127.0.0.1
  port: 27017
  database: base-web
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

reactor:
  threadOfNumber: 10
  agent: com.cai.reactor.core.ParallelAgent
