
server:
  port: 9020


login:
  maxStillState: 300000 # ms
  maxReuse: 1


web:
  accessInterval: 10000 # ms
  isLoose: false

redis:
  host: localhost
  port: 6379
  password:
  database: 3
  max-active: 200
  max-wait: -1
  max-idle: 8
  timeout: 0
  connectionPoolSize: 400

spring:
  main:
    allow-bean-definition-overriding: true
